'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EDW.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to grant select on [{{{schema}}}].[{{{entity}}}.AsIs] to [psa_abstractreader];.
        '''</summary>
        Friend ReadOnly Property PSA_AsIsSecurityDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_AsIsSecurityDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to create trigger [tr : {{{label}}}.AsIs {Reverse DML}] on [{{{schema}}}].[{{{entity}}}.AsIs]
        '''instead of insert,update,delete
        '''as
        '''-- do not alter/add/extend this trigger, or any psa trigger
        '''-- authored by slalom consulting 2014
        '''begin;
        '''   raiserror(N&apos;DML Statements are not allowed on this AsIs view.  Use the Control Abstraction [{{{schema}}}].[{{{entity}}}.Control] instead.&apos;,16,1)
        '''end;.
        '''</summary>
        Friend ReadOnly Property PSA_AsIsTriggerDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_AsIsTriggerDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to create view [{{{schema}}}].[{{{entity}}}.AsIs] with schemabinding --,encryption
        '''as
        '''select
        '''   [psa_entity_key] [AbstractEntityKey],
        '''{{{columnset}}}
        '''from
        '''   {{{domain}}}
        '''where
        '''   [psa_archive_flag]=0
        '''   and
        '''   [psa_active_state]=1
        '''   and
        '''   [psa_current_flag]=1;.
        '''</summary>
        Friend ReadOnly Property PSA_AsIsViewDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_AsIsViewDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to create function [{{{schema}}}].[{{{entity}}}.AsOf]
        ''' (
        '''   @AsOfDateTime datetime2(7)
        ''' ) 
        '''returns table with schemabinding
        '''as return
        '''
        '''select
        '''   [psa_entity_key] [AbstractEntityKey],
        '''{{{columnset}}}
        '''from
        '''   {{{domain}}}
        '''where
        '''   [psa_archive_flag]=0
        '''   and
        '''   [psa_active_state]=1
        '''   and
        '''   [psa_start_period]&lt;=@AsOfDateTime
        '''   and
        '''   isnull([psa_end_period],&apos;9999-12-31 23:59:59.9999999&apos;)&gt;=@AsOfDateTime;.
        '''</summary>
        Friend ReadOnly Property PSA_AsOfFunctionDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_AsOfFunctionDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to grant select on [{{{schema}}}].[{{{entity}}}.AsOf] to [psa_abstractreader];.
        '''</summary>
        Friend ReadOnly Property PSA_AsOfSecurityDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_AsOfSecurityDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to grant select on [{{{schema}}}].[{{{entity}}}.AsWas] to [psa_abstractreader];.
        '''</summary>
        Friend ReadOnly Property PSA_AsWasSecurityDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_AsWasSecurityDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to create trigger [tr : {{{label}}}.AsWas {Reverse DML}] on [{{{schema}}}].[{{{entity}}}.AsWas]
        '''instead of insert,update,delete
        '''as
        '''-- do not alter/add/extend this trigger, or any psa trigger
        '''-- authored by slalom consulting 2014
        '''begin;
        '''   raiserror(N&apos;DML Statements are not allowed on this AsWas view.  Use the Control Abstraction [{{{schema}}}].[{{{entity}}}.Control] instead.&apos;,16,1)
        '''end;.
        '''</summary>
        Friend ReadOnly Property PSA_AsWasTriggerDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_AsWasTriggerDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to create view [{{{schema}}}].[{{{entity}}}.AsWas] with schemabinding
        '''as
        '''select
        '''   [psa_entity_key] [AbstractEntityKey],
        '''   [psa_entity_sequence] [AbstractChangeIncrement],
        '''   [psa_start_period] [AbstractValidFrom],
        '''   isnull([psa_end_period],&apos;9999-12-31 23:59:59.9999999&apos;) [AbstractValidTo],
        '''   [psa_dml_action] [AbstractChangeAction],
        '''{{{columnset}}}
        '''from
        '''   {{{domain}}}
        '''where
        '''   [psa_archive_flag]=0;.
        '''</summary>
        Friend ReadOnly Property PSA_AsWasViewDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_AsWasViewDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to grant select on [{{{schema}}}].[{{{entity}}}.BatchCount] to [psa_etl_manager];.
        '''</summary>
        Friend ReadOnly Property PSA_BatchCountSecurityDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_BatchCountSecurityDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to create trigger [tr : {{{label}}}.BatchCount {Reverse DML}] on [{{{schema}}}].[{{{entity}}}.BatchCount]
        '''instead of insert,update,delete
        '''as
        '''-- do not alter/add/extend this trigger, or any psa trigger
        '''-- authored by slalom consulting 2014
        '''begin;
        '''   raiserror(N&apos;DML Statements are not allowed on this aggregated BatchCount view.  Use the Control Abstraction [{{{schema}}}].[{{{entity}}}.Control] instead to remove individual records.&apos;,16,1)
        '''end;.
        '''</summary>
        Friend ReadOnly Property PSA_BatchCountTriggerDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_BatchCountTriggerDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to create view [{{{schema}}}].[{{{entity}}}.BatchCount] with schemabinding
        '''as
        '''select
        '''   [psa_batch_id] [BatchUID],
        '''   isnull(sum(case when [psa_dml_action]=N&apos;I&apos; then 1 else 0 end),0) [Inserted],
        '''   isnull(sum(case when [psa_dml_action]=N&apos;U&apos; then 1 else 0 end),0) [Updated],
        '''   isnull(sum(case when [psa_dml_action]=N&apos;D&apos; then 1 else 0 end),0) [Deleted],
        '''   isnull(count([psa_entity_key]),0) [Total]
        '''from
        '''   {{{domain}}}
        '''where
        '''   [psa_batch_id] is not null
        '''group by
        '''   [psa_batch_id];.
        '''</summary>
        Friend ReadOnly Property PSA_BatchCountViewDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_BatchCountViewDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to create function [{{{schema}}}].[{{{entity}}}.Changes]
        ''' (
        '''    @CurrentVersion bigint 
        ''' )
        '''returns table with schemabinding
        '''as return
        '''
        '''select
        '''   d.[psa_entity_key] [AbstractEntityKey],
        '''   [psa_dml_action] [AbstractChangeAction],
        '''   case when d.[psa_archive_flag]=1 then N&apos;ARCHIVE&apos; else N&apos;ACTIVE&apos; end [AbstractArchiveActive],
        '''{{{columnset}}}
        '''from
        '''   {{{domain}}} d 
        '''   left join
        '''   changetable(changes {{{domain}}},@CurrentVersion) c on d.[psa_surrogate_key]=c.[psa_surrogate_key]
        '''where
        '''   d.[psa_cu [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PSA_ChangesFunctionDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_ChangesFunctionDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to grant select on [{{{schema}}}].[{{{entity}}}.Changes] to [psa_abstractreader];.
        '''</summary>
        Friend ReadOnly Property PSA_ChangesSecurityDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_ChangesSecurityDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to if not exists(select * from sys.change_tracking_tables where [object_id]=object_id(N&apos;{{{domain}}}&apos;))
        '''alter table {{{domain}}} enable change_tracking
        '''with(track_columns_updated=off);.
        '''</summary>
        Friend ReadOnly Property PSA_ChangeTrackingDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_ChangeTrackingDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to set nocount on;
        '''set quoted_identifier on;
        '''set ansi_nulls on;
        '''
        '''exec sys.sp_executesql 
        '''N&apos;
        '''if object_id(N&apos;&apos;[dbo].[psa_change_tracking_entity_version]&apos;&apos;,N&apos;&apos;U&apos;&apos;) is null begin;
        '''
        '''create table [dbo].[psa_change_tracking_entity_version]
        ''' (
        '''   [psa_object_id] int not null,
        '''   [psa_activity] nvarchar(2) not null,
        '''   primary key clustered ([psa_activity],[psa_object_id]),
        '''
        '''   [psa_schema] sysname not null,
        '''   [psa_entity] sysname not null,
        '''   [psa_domain] as quotename([psa_schema])+N&apos;&apos;.&apos;&apos;+quotename([p [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PSA_ChangeTrackingSystemDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_ChangeTrackingSystemDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to exec [dbo].[sp_manage_column_properties] N&apos;{{{domain}}}&apos;,N&apos;{{{attribute}}}&apos;,N&apos;{{{property}}}&apos;,N&apos;{{{value}}}&apos;;.
        '''</summary>
        Friend ReadOnly Property PSA_ColumnPropertyDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_ColumnPropertyDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to select
        '''   convert(nvarchar(40),[value]) [sig]
        '''from
        '''   sys.extended_properties
        '''where
        '''   [minor_id]=0
        '''   and
        '''   [Name]=N&apos;Construct Signature&apos;
        '''   and
        '''   object_name([major_id])=&apos;{{{entity}}}&apos;
        '''   and
        '''   object_schema_name([major_id])=&apos;{{{schema}}}&apos;;.
        '''</summary>
        Friend ReadOnly Property PSA_ConstructSignatureLookup() As String
            Get
                Return ResourceManager.GetString("PSA_ConstructSignatureLookup", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to create trigger [tr : {{{label}}} {Control Delete}] on [{{{schema}}}].[{{{entity}}}.Control]
        '''instead of delete
        '''as
        '''-- do not alter/add/extend this trigger, or any psa trigger
        '''-- framework authored by slalom consulting 2014
        '''begin;
        '''
        '''   set nocount on;
        '''
        '''   declare @ts datetime2(7)=sysutcdatetime();
        '''   declare @batch uniqueidentifier=convert(uniqueidentifier,context_info());
        '''
        '''   with [delete_source] as
        '''    (
        '''      select
        '''{{{columnset}}}
        '''         @batch [psa_batch_id],
        '''         [dbo].[psa_hash]((s [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PSA_ControlDeleteDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_ControlDeleteDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to create trigger [tr : {{{label}}} {Control Insert}] on [{{{schema}}}].[{{{entity}}}.Control]
        '''instead of insert
        '''as
        '''-- do not alter/add/extend this trigger, or any psa trigger
        '''-- authored by slalom consulting 2014
        '''begin;
        '''
        '''   set nocount on;
        '''
        '''   declare @ts datetime2(7)=sysutcdatetime();
        '''   declare @batch uniqueidentifier=convert(uniqueidentifier,context_info());
        '''
        '''   insert {{{domain}}}
        '''    (
        '''{{{columnset}}}
        '''      [psa_batch_id],
        '''      [psa_hash_id],
        '''      [psa_start_period]
        '''    )
        '''   select
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PSA_ControlInsertDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_ControlInsertDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to grant select,insert,update,delete on [{{{schema}}}].[{{{entity}}}.Control] to [psa_etl_manager];.
        '''</summary>
        Friend ReadOnly Property PSA_ControlSecurityDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_ControlSecurityDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to create trigger [tr : {{{label}}} {Control Update}] on [{{{schema}}}].[{{{entity}}}.Control]
        '''instead of update
        '''as
        '''-- do not alter/add/extend this trigger, or any psa trigger
        '''-- authored by slalom consulting 2014
        '''begin;
        '''
        '''   set nocount on;
        '''
        '''   declare @ts datetime2(7)=sysutcdatetime();
        '''   declare @batch uniqueidentifier=convert(uniqueidentifier,context_info());
        '''
        '''{{{updatekeyset}}}
        '''   with [update_source] as
        '''    (
        '''      select
        '''{{{columnset}}}
        '''         @batch [psa_batch_id],
        '''         [dbo].[ps [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PSA_ControlUpdateDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_ControlUpdateDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to create view [{{{schema}}}].[{{{entity}}}.Control] with schemabinding
        '''as
        '''select
        '''{{{columnset}}}
        '''from
        '''   {{{domain}}}
        '''where
        '''   [psa_current_flag]=1;.
        '''</summary>
        Friend ReadOnly Property PSA_ControlViewDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_ControlViewDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to if not exists(select 1 from sys.change_tracking_databases where [database_id]=db_id()) begin;
        '''   alter database [{{{db}}}] set change_tracking=on (change_retention=5 days,auto_cleanup=on);
        '''end;.
        '''</summary>
        Friend ReadOnly Property PSA_DatabaseChangeTrackingDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_DatabaseChangeTrackingDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to --:SETVAR DatabaseName &apos;[edw_psa]&apos;
        '''--:SETVAR Path &apos;A:\SQL\Data\&apos;
        '''
        '''use [master];
        '''go
        '''
        '''create database [edw_psa]
        '''on primary (NAME = N&apos;psa_primary&apos;,FILENAME=N&apos;A:\SQL\Data\psa_primary.mdf&apos;,SIZE=5120KB,MAXSIZE=UNLIMITED,FILEGROWTH=1024KB), 
        '''filegroup [SNK] (NAME = N&apos;psa_snk&apos;, FILENAME=N&apos;A:\SQL\Data\psa_snk.ndf&apos;,SIZE=5120KB,MAXSIZE=UNLIMITED,FILEGROWTH=1024KB),
        '''filegroup [SPK]
        ''' (
        '''   NAME = N&apos;psa_spk&apos;, FILENAME = N&apos;A:\SQL\Data\psa_spk.ndf&apos; , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
        '''  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PSA_DatabaseTemplate() As String
            Get
                Return ResourceManager.GetString("PSA_DatabaseTemplate", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to if object_id(&apos;[{{{schema}}}].[{{{entity}}}.AsOf]&apos;,N&apos;IF&apos;) is not null drop function [{{{schema}}}].[{{{entity}}}.AsOf];
        '''if object_id(&apos;[{{{schema}}}].[{{{entity}}}.Changes]&apos;,N&apos;IF&apos;) is not null drop function [{{{schema}}}].[{{{entity}}}.Changes];
        '''
        '''if object_id(&apos;[{{{schema}}}].[{{{entity}}}.ProcessLoad]&apos;,N&apos;P&apos;) is not null drop procedure [{{{schema}}}].[{{{entity}}}.ProcessLoad];
        '''if object_id(&apos;[{{{schema}}}].[{{{entity}}}.ProcessArchive]&apos;,N&apos;P&apos;) is not null drop procedure [{{{schema}}}].[{{{entity}}}.ProcessA [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PSA_DropRelatedObjects() As String
            Get
                Return ResourceManager.GetString("PSA_DropRelatedObjects", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to if object_id(N&apos;[{{{schema}}}].[tr : {{{label}}} {Temporal Governor}]&apos;,N&apos;TR&apos;) is not null begin;
        '''   drop trigger [{{{schema}}}].[tr : {{{label}}} {Temporal Governor}];
        '''end;.
        '''</summary>
        Friend ReadOnly Property PSA_DropTemporalGovernorDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_DropTemporalGovernorDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to if object_id(N&apos;[dbo].[psa_hash]&apos;,N&apos;FN&apos;) is null begin;
        '''
        '''   exec sys.sp_executesql
        '''   N&apos;
        '''   create function [dbo].[psa_hash] 
        '''    (
        '''      @string nvarchar(max)
        '''    ) 
        '''   returns varbinary(20) with encryption
        '''   as 
        '''   begin;
        '''      return master.dbo.[fn_hash](@string);
        '''   end;
        '''   &apos;
        '''   exec sys.sp_MS_marksystemobject &apos;psa_hash&apos;;
        '''
        '''end;.
        '''</summary>
        Friend ReadOnly Property PSA_HashingAlgorithmForPSA() As String
            Get
                Return ResourceManager.GetString("PSA_HashingAlgorithmForPSA", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to select
        '''   db_name() [database_name],
        '''   @@servername [instance_name],
        '''   serverproperty(&apos;productlevel&apos;) [product_level],
        '''   serverproperty(&apos;edition&apos;) [edition],
        '''   parsename(convert(nvarchar(50),serverproperty(&apos;productversion&apos;)),4) [version];.
        '''</summary>
        Friend ReadOnly Property PSA_InstanceProperties() As String
            Get
                Return ResourceManager.GetString("PSA_InstanceProperties", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to -- create &apos;upsert queue&apos; abstraction
        '''if object_id(N&apos;[{{{schema}}}].[{{{entity}}}.UpsertQueue]&apos;,N&apos;U&apos;) is not null drop table [{{{schema}}}].[{{{entity}}}.UpsertQueue];
        '''   
        '''create table [{{{schema}}}].[{{{entity}}}.UpsertQueue]
        ''' (
        '''   [psa_stage_key] int identity (1,1),
        '''   constraint [pk : {{{schema}}}.{{{entity}}}.UpsertQueue {PSA Surrogate Key}]
        '''   primary key clustered ([psa_stage_key])
        '''   with (data_compression=page,fillfactor=95) on [TMP],
        '''
        '''{{{bichunk}}}
        '''{{{attrchunk}}}
        '''
        '''   constraint [ak : { [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PSA_LoadQueueDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_LoadQueueDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to select
        '''   convert(nvarchar(40),[value]) [sig]
        '''from
        '''   sys.extended_properties
        '''where
        '''   [minor_id]=0
        '''   and
        '''   [Name]=N&apos;Logical Signature&apos;
        '''   and
        '''   object_name([major_id])=&apos;{{{entity}}}&apos;
        '''   and
        '''   object_schema_name([major_id])=&apos;{{{schema}}}&apos;;.
        '''</summary>
        Friend ReadOnly Property PSA_LogicalSignatureLookup() As String
            Get
                Return ResourceManager.GetString("PSA_LogicalSignatureLookup", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to if object_id(N&apos;{{{domain}}}&apos;,N&apos;U&apos;) is not null begin;
        '''
        '''   exec [sys].[sp_rename] N&apos;{{{domain}}}&apos;, N&apos;{{{label}}}.{{{ext}}}&apos;;
        '''   alter schema [dbo] transfer [{{{schema}}}].[{{{label}}}.{{{ext}}}];
        '''
        '''   declare @x int;
        '''
        '''   select
        '''      @x=[rows]
        '''   from
        '''      sys.partitions
        '''   where
        '''      [object_id]=object_id(N&apos;[dbo].[{{{label}}}.{{{ext}}}]&apos;,N&apos;U&apos;)
        '''      and
        '''      [partition_number]=1;
        '''
        '''   if @x=0 begin;
        '''      drop table [dbo].[{{{label}}}.{{{ext}}}];
        '''   end else begin;
        '''
        '''      exec [sys].[sp [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PSA_RenameDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_RenameDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to if not exists(select 1 from sys.sysusers where [name]=N&apos;psa_owner&apos;) begin;
        '''   create role [psa_owner] authorization [db_owner];
        '''end;
        '''
        '''if not exists(select 1 from sys.sysusers where [name]=N&apos;psa_abstractreader&apos;) begin;
        '''   create role [psa_abstractreader] authorization [psa_owner];
        '''end;
        '''
        '''if not exists(select 1 from sys.sysusers where [name]=N&apos;psa_etl_manager&apos;) begin;
        '''   create role [psa_etl_manager] authorization [psa_owner];
        '''end;.
        '''</summary>
        Friend ReadOnly Property PSA_RoleDefinitions() As String
            Get
                Return ResourceManager.GetString("PSA_RoleDefinitions", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to set nocount on;
        '''set quoted_identifier on;
        '''set ansi_nulls on;
        '''set ansi_warnings on;
        '''
        '''if not exists (select * from sys.sysusers where [name]=&apos;psa_owner&apos;) begin;
        '''   create role [psa_owner] authorization [db_owner];
        '''end;
        '''
        '''if not exists (select * from sys.sysusers where [name]=&apos;psa_etl_manager&apos;) begin;
        '''   create role [psa_etl_manager] authorization [psa_owner];
        '''end;
        '''
        '''if not exists (select * from sys.sysusers where [name]=&apos;psa_abstractreader&apos;) begin;
        '''   create role [psa_abstractreader] authorization [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PSA_SchemaDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_SchemaDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to if not exists (select * from sys.sequences where [name]=N&apos;{{{entity}}}.SPK&apos; and object_schema_name([object_id])=N&apos;{{{schema}}}&apos;) begin;
        '''   exec sys.sp_executesql N&apos;create sequence [{{{schema}}}].[{{{entity}}}.SPK] start with 1 increment by 1 minvalue 1 cycle cache 1000;&apos;
        '''end;.
        '''</summary>
        Friend ReadOnly Property PSA_SequenceDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_SequenceDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to set nocount on;
        '''set quoted_identifier on;
        '''set ansi_nulls on;
        '''set ansi_warnings on;
        '''
        '''create table {{{domain}}}
        ''' (
        '''   [psa_surrogate_key] bigint not null
        '''   constraint [df : {{{label}}} {SPK Sequence Number}]
        '''   default (next value for [{{{schema}}}].[{{{entity}}}.SPK]),
        '''
        '''   constraint [pk : {{{label}}} {Surrogate Primary Key}]
        '''   primary key nonclustered ([psa_surrogate_key])
        '''   with (data_compression=page,fillfactor=95) on [SPK],
        '''
        '''   [psa_entity_key] bigint not null
        '''   constraint [df : {{{la [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PSA_TableDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_TableDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to exec [dbo].[sp_manage_table_properties] N&apos;{{{domain}}}&apos;,N&apos;{{{property}}}&apos;,N&apos;{{{value}}}&apos;;.
        '''</summary>
        Friend ReadOnly Property PSA_TablePropertyDefintion() As String
            Get
                Return ResourceManager.GetString("PSA_TablePropertyDefintion", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to create trigger [tr : {{{label}}} {Temporal Governor}] on {{{domain}}}
        '''after update
        '''as
        '''-- do not alter/add/extend this trigger, or any psa trigger
        '''-- authored by slalom consulting 2014
        '''begin;
        '''
        '''   set nocount on;
        '''
        '''   insert {{{domain}}}
        '''    (
        '''      [psa_entity_key],
        '''      [psa_entity_sequence],
        '''      [psa_start_period],
        '''      [psa_end_period],
        '''      [psa_active_state],
        '''      [psa_batch_id],
        '''      [psa_archive_flag],
        '''{{{insertset}}}
        '''      [psa_hash_id]
        '''    )
        '''   select
        '''      d.[psa_entity_ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PSA_TemporalGovernorDefinition() As String
            Get
                Return ResourceManager.GetString("PSA_TemporalGovernorDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to if object_id(&apos;[dbo].[sp_manage_column_properties]&apos;,N&apos;P&apos;) is not null drop procedure [dbo].[sp_manage_column_properties];
        '''
        '''exec sys.sp_executesql
        '''N&apos;
        '''create procedure [dbo].[sp_manage_column_properties]
        ''' (
        '''   @domain_name sysname,
        '''   @column_name sysname,
        '''   @property sysname,
        '''   @property_value sql_variant
        ''' ) with encryption
        '''as
        '''
        '''set nocount on;
        '''
        '''declare
        '''   @object_id int,
        '''   @column_id int;
        '''
        '''select
        '''   @object_id=object_id(@domain_name);
        '''
        '''if @object_id is null begin;
        '''   print N&apos;&apos;Domain  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SYS_ColumnMetadataDefinition() As String
            Get
                Return ResourceManager.GetString("SYS_ColumnMetadataDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to select
        '''   db_name() [database_name],
        '''   [compatibility_level]
        '''from 
        '''   sys.databases 
        '''where 
        '''   [database_id]=db_id();.
        '''</summary>
        Friend ReadOnly Property SYS_DatabaseProperties() As String
            Get
                Return ResourceManager.GetString("SYS_DatabaseProperties", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to select * from [dbo].[psa_attribute_definition] where 1=1.
        '''</summary>
        Friend ReadOnly Property SYS_PSAAttributeDefinition() As String
            Get
                Return ResourceManager.GetString("SYS_PSAAttributeDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to with x as
        ''' (
        '''   select
        '''      [psa_schema],
        '''      [psa_entity],
        '''      row_number() over (partition by [psa_schema],[psa_entity] order by [psa_attribute_ordinal],[psa_attribute]) [ord],
        '''      convert(nvarchar(max),
        '''      right(convert(nvarchar(42),hashbytes(N&apos;sha1&apos;,[psa_attribute]),1),40)+N&apos; : &apos;+
        '''      right(convert(nvarchar(42),hashbytes(N&apos;sha1&apos;,[psa_attribute_datatype]),1),40)+N&apos; : &apos;+
        '''      right(convert(nvarchar(42),hashbytes(N&apos;sha1&apos;,convert(nvarchar(10),[psa_attribute_ordinal])),1),40)+N&apos; : &apos;+
        '''  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SYS_PSAEntityDefinition() As String
            Get
                Return ResourceManager.GetString("SYS_PSAEntityDefinition", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to set nocount on;
        '''set quoted_identifier on;
        '''set ansi_nulls on;
        '''set ansi_warnings on;.
        '''</summary>
        Friend ReadOnly Property SYS_QueryBehavior() As String
            Get
                Return ResourceManager.GetString("SYS_QueryBehavior", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to    ______     __             _____                  ____  _          
        '''  / __/ /__ _/ /__  __ _    / ___/__  ___  _____ __/ / /_(_)__  ___ _
        ''' _\ \/ / _ `/ / _ \/  &apos; \  / /__/ _ \/ _ \(_-&lt; // / / __/ / _ \/ _ `/
        '''/___/_/\_,_/_/\___/_/_/_/  \___/\___/_//_/___|_,_/_/\__/_/_//_/\_, / 
        '''                                                              /___/.
        '''</summary>
        Friend ReadOnly Property SYS_SlalomTextArt1() As String
            Get
                Return ResourceManager.GetString("SYS_SlalomTextArt1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to if object_id(&apos;[dbo].[sp_manage_table_properties]&apos;,N&apos;P&apos;) is not null drop procedure [dbo].[sp_manage_table_properties];
        '''
        '''exec sys.sp_executesql
        '''N&apos;
        '''create procedure [dbo].[sp_manage_table_properties]
        ''' (
        '''   @domain_name sysname,
        '''   @property sysname,
        '''   @property_value sql_variant
        ''' ) with encryption
        '''as
        '''
        '''set nocount on;
        '''
        '''declare
        '''   @object_id int;
        '''
        '''select
        '''   @object_id=object_id(@domain_name);
        '''
        '''if @object_id is null begin;
        '''   print N&apos;&apos;Domain &apos;&apos;+isnull(@domain_name,N&apos;&apos;{NULL}&apos;&apos;)+N&apos;&apos; does not  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SYS_TableMetadataDefinition() As String
            Get
                Return ResourceManager.GetString("SYS_TableMetadataDefinition", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
